import type {Product} from "@/components/ProductCard";
export const allProducts: Product[] = [
    {
        id: 1,
        image: "/flash/hv-g92.webp",
        title: "HAVIT HV-G92 Gamepad",
        price: 1200,
        original: 1600,
        discount: 40,
        rating: 4.5,
        reviews: 88,
        type: "flash-sale",
        category: "Gaming",
    },
    {
        id: 2,
        image: "/flash/ak-900.jpg",
        title: "AK-900 Wired Keyboard",
        price: 960,
        original: 1160,
        discount: 35,
        rating: 4.0,
        reviews: 75,
        type: "flash-sale",
        category: "Computers",
    },
    {
        id: 3,
        image: "/flash/monitor.webp",
        title: "IPS LCD Gaming Monitor",
        price: 37000,
        original: 40000,
        discount: 30,
        rating: 4.8,
        reviews: 99,
        type: "flash-sale",
        category: "TV & Audio",
    },
    {
        id: 4,
        image: "/flash/mouse.webp",
        title: "Ergonomic Gaming Mouse",
        price: 750,
        original: 850,
        discount: 25,
        rating: 4.3,
        reviews: 54,
        type: "flash-sale",
        category: "Gaming",
    },
    {
        id: 5,
        image: "/flash/headset.jpg",
        title: "Noise-Cancelling Headset",
        price: 1400,
        original: 2000,
        discount: 30,
        rating: 4.6,
        reviews: 62,
        type: "flash-sale",
        category: "Headphones",
    },
    {
        id: 6,
        image: "/flash/chair.webp",
        title: "S-Series Comfort Chair",
        price: 3750,
        original: 3900,
        discount: 25,
        rating: 4.7,
        reviews: 82,
        type: "flash-sale",
        category: "Accessories",
    },
    {
        id: 7,
        image: "/flash/laptop.webp",
        title: 'HP 14s-dq3139TU Intel Celeron N4500 14" FHD Laptop',
        price: 39500,
        original: 42000,
        discount: 15,
        rating: 4.4,
        reviews: 68,
        type: "flash-sale",
        category: "Computers",
    },
    {
        id: 8,
        image: "/flash/tablet.webp",
        title: 'HONOR Pad X8a 4GB RAM 128GB Storage 11" Tablet',
        price: 19900,
        original: 21000,
        discount: 30,
        rating: 4.0,
        reviews: 37,
        type: "flash-sale",
        category: "Wearables",
    },
    {
        id: 9,
        image: "/flash/usbhub.webp",
        title: "USB 3.0 4-in-1 Hub",
        price: 700,
        original: 800,
        discount: 33,
        rating: 4.1,
        reviews: 29,
        type: "flash-sale",
        category: "Accessories",
    },
    {
        id: 10,
        image: "/flash/powerbank.webp",
        title: "Hoco J89 10000mAh 20W Fast Charging Digital Display Power Bank",
        price: 1090,
        original: 1310,
        discount: 30,
        rating: 4.3,
        reviews: 41,
        type: "flash-sale",
        category: "Accessories",
    },
    {
        id: 11,
        title: "Breed Dry Dog Food",
        image: "/best/dogfood.jpg",
        price: 1200,
        original: 1600,
        discount: 25,
        rating: 4.5,
        reviews: 88,
        type: "best-seller",
        category: "Smart Home",
    },
    {
        id: 12,
        title: "CANON EOS 200D Mark-II",
        image: "/best/camera.jpg",
        price: 37000,
        original: 40000,
        discount: 10,
        rating: 4.8,
        reviews: 99,
        type: "best-seller",
        category: "Camera",
    },
    {
        id: 13,
        title: "ASUS FHD Gaming Laptop",
        image: "/best/laptop.jpg",
        price: 39500,
        original: 42000,
        discount: 15,
        rating: 4.4,
        reviews: 68,
        type: "best-seller",
        category: "Computers",
    },
    {
        id: 14,
        title: "Curology Product Set",
        image: "/best/curology2.png",
        price: 1990,
        original: 2100,
        discount: 5,
        rating: 4.0,
        reviews: 37,
        type: "best-seller",
        category: "Smart Home",
    },
    {
        id: 15,
        title: "Kids Electric Car",
        image: "/best/kidscar.jpg",
        price: 10900,
        original: 13100,
        discount: 17,
        rating: 4.3,
        reviews: 41,
        type: "best-seller",
        category: "Accessories",
    },
    {
        id: 16,
        title: "Jr. Zoom Soccer Cleats",
        image: "/best/cleats.jpg",
        price: 750,
        original: 850,
        discount: 12,
        rating: 4.3,
        reviews: 54,
        type: "best-seller",
        category: "Wearables",
    },
    {
        id: 17,
        title: "GP1 Shooter USB Gamepad",
        image: "/best/gamepad.jpg",
        price: 1400,
        original: 2000,
        discount: 30,
        rating: 4.6,
        reviews: 62,
        type: "best-seller",
        category: "Gaming",
    },
    {
        id: 18,
        title: "Quilted Satin Jacket",
        image: "/best/satin.jpg",
        price: 3750,
        original: 3900,
        discount: 5,
        rating: 4.7,
        reviews: 82,
        type: "best-seller",
        category: "Wearables",
    },
]